Chore/update test workflow
nimblehq/elixir-templates pull request #112
Opened 2021-05-31 03:34 UTC by junan

https://github.com/nimblehq/elixir-templates/issues/??

## What happened

Describe the big picture of your changes here to communicate to the team why we should accept this pull request. 
 
## Insight

Describe in details how to test the changes, which solution you tried but did not go with, referenced documentation is welcome as well.
 
## Proof Of Work

Show us the implementation: screenshots, gif, etc.

2021-07-23 07:12 UTC, andyduong1920 approved these changes

2021-07-23 07:16 UTC, andyduong1920 commented
@junan Rebase required 🙏

2021-07-23 07:51 UTC, olivierobert commented
@junan Please rebase so that this can be merged in the upcoming release

2021-07-23 07:53 UTC, olivierobert requested changes

2021-07-23 07:53 UTC, olivierobert commented on priv/templates/nimble_template/.github/workflows/test.yml.eex
> +      - name: Setup Elixir
To be a verb it should `Set up`. In one word `Setup` is a noun.

2021-08-15 08:30 UTC, longnd approved these changes

2021-08-17 01:50 UTC, bterone approved these changes

2021-12-01 11:06 UTC, andyduong1920 commented
Please rebase this PR @junan  the test was fixed on #128 👍

2021-12-03 07:44 UTC, junan commented
>  Please rebase this PR @junan the test was fixed on #128 👍

@andyduong1920 Test has not been fixed, after rebase it is still failing. To verify it, I created new branch a committed a small [commit](https://github.com/nimblehq/elixir-templates/commit/eb913628896cf40e3c1a7b3cf8d175a16625f64d), but still [fails](https://github.com/nimblehq/elixir-templates/runs/4405259299?check_suite_focus=true) 💭

2021-12-03 09:02 UTC, andyduong1920 commented
> > Please rebase this PR @junan the test was fixed on #128 👍
> 
> @andyduong1920 Test has not been fixed, after rebase it is still failing. To verify it, I created new branch a committed a small [commit](https://github.com/nimblehq/elixir-templates/commit/eb913628896cf40e3c1a7b3cf8d175a16625f64d), but still [fails](https://github.com/nimblehq/elixir-templates/runs/4405259299?check_suite_focus=true) 💭

It's another issue due to the upstream introduced by just today I guess @junan 😂 while the other issue was fixed in #128

2021-12-22 07:14 UTC, rosle commented on .github/workflows/test_live_variant_on_standard_liveview_project.yml
> +
```suggestion
```

2021-12-22 07:42 UTC, merged